[project]
name = "odoo-addons-sygel-technology-sy-general-connector"
version = "18.0.20260417.5"
dependencies = [
    "odoo-addon-ecommerce_connector==18.0.*",
    "odoo-addon-ecommerce_connector_sale_invoice_policy==18.0.*",
    "odoo-addon-ecommerce_connector_sale_order_type==18.0.*",
    "odoo-addon-ecommerce_connector_sii==18.0.*",
    "odoo-addon-product_management_connector==18.0.*",
    "odoo-addon-stock_check_connector==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
